### ISSUE TITLE
Card view doesn't work and throws an error in both demo'land and rally100

### ISSUE THREAD

**Issue by dhyoung** [RallyCommunity/PSITrackingApp#13]
Here is the error I receive if clicking on card view: "The currently selected Group By field cannot be found on all card types. Some card types may not appear."

**Comment by krmorse** [comment]
@dhyoung, would you be willing to give this updated version a go and see how it works for you?  it should have new filtering and a bunch of other fixes.

https://raw.githubusercontent.com/RallyCommunity/PSITrackingApp/91dde450cb35e05a01372ad90b293142e0c9c60f/deploy/App-uncompressed.html

You can copy/paste the contents of that file ^^ into a custom html app and test it side by side with the existing one.

If that all looks good we'll get this merged and updated in the community app catalog.

**Comment by dhyoung** [comment]
@krmorse I gave the new version a spin. I can now switch to Board (card) view and see the Feature cards. In Grid view it no longer shows Features, just, Stories, Defects, Test Sets and their children. See attached screenshot.
<img width="1661" alt="screen shot 2018-04-17 at 7 37 57 pm" src="https://user-images.githubusercontent.com/1590692/38904246-497404cc-4277-11e8-96ac-3e0e5fd97632.png">

**Comment by krmorse** [comment]
@dhyoung That's super weird.  I'll have to dig in to that!  In my local testing I still get features showing up in my grid.  Any chance you could share that page somewhere I could access?  Is it in a demo sub?

**Comment by dhyoung** [comment]
@krmorse This is in our demo@prod subscription. I'll 1:1 chat you in Flowdock with my log in credentials for you to see this behavior

**Comment by krmorse** [comment]
fixed in #16
