### ISSUE TITLE
Filtering Needed

### ISSUE THREAD

**Issue by amykmeyers** [RallyCommunity/PSITrackingApp#17]
Is it possible to update this app to take advantage of advanced filtering or querying?

**Comment by krmorse** [comment]
Yeah, totally.  #16 contains a bunch of improvements, including this.  Not sure on timing for getting it merged, but hoping to find some time in the next couple months to do another refresh of community app catalog (some new apps, some updates to existing apps).  @anagram15 ^^

**Comment by krmorse** [comment]
@amykmeyers, would you be willing to give this updated version a go and see how it works for you?  it should have new filtering and a bunch of other fixes.

https://raw.githubusercontent.com/RallyCommunity/PSITrackingApp/91dde450cb35e05a01372ad90b293142e0c9c60f/deploy/App-uncompressed.html

You can copy/paste the contents of that file ^^ into a custom html app and test it side by side with the existing one.

If that all looks good we'll get this merged and updated in the community app catalog.

**Comment by amykmeyers** [comment]
@krmorse - sorry I didn't get a chance to test this earlier.   Loading today and testing!

**Comment by krmorse** [comment]
@amykmeyers, i think the code linked above may have been in a bad state.  try this one?  

https://raw.githubusercontent.com/RallyCommunity/PSITrackingApp/daf2b7e40d43f4da04b2f8488088e1564e1e3013/deploy/App.html

**Comment by krmorse** [comment]
fixed in #16
