### ISSUE TITLE
Issue when switching views

### ISSUE THREAD

**Issue by gmartinez170479** [RallyCommunity/PSITrackingApp#18]
Getting an issue when moving to Board view

![image](https://user-images.githubusercontent.com/19513192/38830423-18d3327c-4171-11e8-9a18-f2cee3aa399a.png)

**Comment by krmorse** [comment]
Yep, the board view is basically totally broken.  I'm actually working on a fairly significant upgrade of this app currently.  I was leaning toward actually just removing the board view altogether.  The problem you're seeing is that the grid view is showing anything in the release- stories, defects, features, etc.  Those artifact types don't share a common field that could be used for columns on a board view.

If we wanted to have a board view, wow would you want it to work?  Only features?  Only team level artifacts?

**Comment by krmorse** [comment]
I think that makes the most sense.  Thanks for your input!  Hopefully I'll have something put together here soon- would you be willing to kick the tires and give me some feedback at that point?

**Comment by krmorse** [comment]
@gmartinez170479 , would you be willing to give this updated version a go and see how it works for you?  it should have new filtering and a bunch of other fixes.

https://raw.githubusercontent.com/RallyCommunity/PSITrackingApp/91dde450cb35e05a01372ad90b293142e0c9c60f/deploy/App-uncompressed.html

You can copy/paste the contents of that file ^^ into a custom html app and test it side by side with the existing one.

If that all looks good we'll get this merged and updated in the community app catalog.

**Comment by gmartinez170479** [comment]
Sure man, more than Happy to help here.

FYI 
I’m agile coach at T-Mobile for multiple programs (large ones) so we use a lot your reports…. THANKS!!!!

**Comment by gmartinez170479** [comment]
Hey, I just noticed that bunch of user Stories are coming at the same level as the feature, even thought they have feature assigned, the feature is not showing there.

**Comment by krmorse** [comment]
In grid view it should show anything at the root level that is associated with the selected release.  Is that not what you're seeing?

**Comment by gmartinez170479** [comment]
Here we go…

1) When switching between list to grid, the features showed up, but still seeing the “warning” message


2) In the list view, I’m seeing listed user stories at the same level as features. The problem is that those stories already have a feature assigned and those are not listed as a child objects for that feature.

**Comment by krmorse** [comment]
OK, I got the warning message fixed in board mode.  I'm curious on 2) however.  I'm unable to repro that.  I have a story that is in the release and also parented beneath a feature in the release, and it shows up in both places.

**Comment by gmartinez170479** [comment]
I’ll check the content (security constraints), and see if I can take a screenshot.

**Comment by krmorse** [comment]
here's a new version:  https://raw.githubusercontent.com/RallyCommunity/PSITrackingApp/daf2b7e40d43f4da04b2f8488088e1564e1e3013/deploy/App.html

i just realized when testing this against the old version that the old one didn't even show stories, etc. in grid view- only features, which you can then drill into.  that was my bad!

hope this is looking more like you'd expect...

**Comment by krmorse** [comment]
fixed in #16
