### ISSUE TITLE
Discussion column doesn't show the discussion icon

### ISSUE THREAD

**Issue by sficarrotta** [RallyCommunity/PSITrackingApp#2]
Your Portfolio drilldown app  does show the Discussions properly, but not the PSI Tracking app
![screen shot 2014-07-01 at 8 07 38 am](https://cloud.githubusercontent.com/assets/1590338/3442703/7aaf56da-0118-11e4-94dc-7e205cc774bb.png)

**Comment by krmorse** [comment]
@sficarrotta would you be willing to give this updated version a go and see how it works for you? it should have new filtering and a bunch of other fixes.

https://raw.githubusercontent.com/RallyCommunity/PSITrackingApp/91dde450cb35e05a01372ad90b293142e0c9c60f/deploy/App-uncompressed.html

You can copy/paste the contents of that file ^^ into a custom html app and test it side by side with the existing one.

If that all looks good we'll get this merged and updated in the community app catalog.

**Comment by krmorse** [comment]
fixed in #16
