### ISSUE TITLE
App depends on lowest level PI being named Feature

### ISSUE THREAD

**Issue by jcwaco** [RallyCommunity/PSITrackingApp#22]
Hello,

While most organizations use 'Feature' as the name for the lowest level PI, some don't. This app is using Portfolio Item/Feature as the model to to load PI's and has a number of other 'Feature' references. The Readme.md implies that it is working with Features. But it doesn't say that is a pre-requisite.

At a minimum we need to document that it depends on the lowest level PI being called 'Feature'. Here is how it will fail if that is not the case:

![screen shot 2018-05-21 at 12 32 44 pm](https://user-images.githubusercontent.com/7408019/40321209-eaa84588-5cf3-11e8-963b-db1f599ff96d.png)

**Comment by krmorse** [comment]
d'oh!  that's definitely an issue!  this shouldn't be too hard to fix...

**Comment by plindo1999** [comment]
I would love to use this app but we do not use Feature as the lowest level Portfolio item

**Comment by plindo1999** [comment]
I tested the fix for the lowest level Portfolio "not" being named Feature - It works Thanks!

**Comment by plindo1999** [comment]
The pop out for the Pie chart does work; click on pie object i get a blank screen

**Comment by jcwaco** [comment]
Hi @plindo1999 ,

The popout chart works for me. Is it possible that you have a 'pop up' blocker inhibiting this in the browser you are using? Or are you getting a blank popup window? 
P.S. I am not a developer for this App. Just a user.
![screen shot 2018-07-13 at 6 27 53 am](https://user-images.githubusercontent.com/7408019/42689586-7ebee2f4-8666-11e8-9d09-8ddeba5559c9.png)

**Comment by plindo1999** [comment]
It was too much data.  I needed to be patient. Chart works!

**Comment by krmorse** [comment]
Fixed in v1.0.3, should be in community app catalog on rally1 tomorrow...
